### ISSUE TITLE
Convert html files to handlebars

### ISSUE THREAD

**Issue by riezen** [Jasper8628/Group_Project_2#14]
Would Rita like to move common html code to /templates/main.handlebars and then pop index and register into handlebars format using {{{BODY}}}.

**Comment by sevenspell** [comment]
Hey Stew, i think we should leave this as HTML. The handlebars page should be the chess.handlebars where the js would go to mysql to retrieve user data and putting it back into the chess.handlebars page with username for the chatbox and players

**Comment by riezen** [comment]
Agreed.
